[env:xiao_nrf52840]
platform = nordicnrf52
board = seeed_xiao_nrf52840
framework = arduino
lib_deps =
  NimBLE-Arduino
  Arduino_BMI270_BMM150

; Adjust upload_port if needed, or run 'pio device list' to discover.
; To build: pio run
; To upload: pio run -t upload -e xiao_nrf52840
